[uwsgi]
# socket: UNIX/TCP-сокет для привязки сервера.
# (Опция предназначена для связи с каким-либо сторонним маршрутизатором, например NGINX)
socket=/code/educa/uwsgi_app.sock
# chdir: путь к каталогу проекта, чтобы сервер WSGI переходил в этот каталог перед загрузкой приложения Python.
chdir = /code/educa/
# module: подлежащий использованию модуль WSGI. Он устанавливается для вызываемого приложения,
# содержащегося в модуле wsgi проекта.
module=educa.wsgi:application
# master: активировать ведущий процесс.
master=true
# chmod-socket: права доступа к файлу сокета. В данном случае используется 666,
# чтобы NGINX мог читать/писать сокет.
chmod-socket=666
# uid: ИД пользователя процесса после его запуска
uid=www-data
# gid: ID группы процесса после его запуска
gid=www-data
# vacuum: наличие значения true сообщает серверу uWSGI, что следует
# очистить все временные файлы или UNIX-сокеты, которые он создает.
vacuum=true